<pre class='metadata'>
Title: CSS Scroll Snap Stop: before
Shortname: scroll-snap-stop-before
Level: None
Status: w3c/UD
Repository: explainers-by-googlers/scroll-snap-stop-before
URL: https://explainers-by-googlers.github.io/scroll-snap-stop-before
Editor: David Liu, Google https://google.com, lcdavid@google.com
Abstract: This specification proposes the 'before' value for the 'scroll-snap-stop' CSS property, allowing snap areas to halt inertial scrolling at the snap target immediately preceding the specified element.
Markup Shorthands: markdown yes, css no
Complain About: accidental-2119 yes, missing-example-ids yes
Assume Explicit For: yes
Die On: warning
WPT Path Prefix: TODO-API-LABEL
WPT Display: closed
Include MDN Panels: if possible
Include Can I Use Panels: yes
</pre>

Introduction {#intro}
=====================

For now, see the <a href=[REPOSITORYURL]>explainer</a>.

See [https://garykac.github.io/procspec/](https://garykac.github.io/procspec/),
[https://dlaliberte.github.io/bikeshed-intro/index.html](https://dlaliberte.github.io/bikeshed-intro/index.html),
and [https://speced.github.io/bikeshed/](https://speced.github.io/bikeshed/) to get started on your
specification.
